### PR TITLE
WIP: Update to bats tests. Remove old tests

### PR DESCRIPTION
**Pull request by avdata99**
Done
 - Removed old test
 - Added bats file
 - updated test container
 - connect with new versions of catalog-db and catalog-solr

Notes:
CKAN from OKF [requires](https://github.com/okfn/docker-ckan/blob/master/ckan-base/setup/prerun.py#L194) the _datastore_ database. Without datastore we do not create the sysadmin user require to run tests.
In old GSA docker image this DB is not required and is added with datapusher

Note: Tests fails since I'm usin [catalog-db](https://github.com/avdata99/catalog-db/pull/1) and [catalog-solr](https://github.com/avdata99/catalog-solr/pull/1) from updates not yet validated.

### CODE REVIEW

**Comment by jbrown-xentity** [comment]
Looks like you pulled these tests from inventory. You may need to pull over the "seed" functionality for some of the tests, as some of the tests validate that data is loaded (among other things)... @avdata99

**Comment by adborden** [comment]
Interesting that CI is green even though the tests didn't pass.

**Comment by adborden** [comment]
You'll want to pick up this fix so CI actually fails when there is an error: https://github.com/GSA/catalog-app/pull/130

**Comment by avdata99** [comment]
I added the ´--abort-on-container-exit´ and now tests are failing

**Comment by avdata99** [comment]
Closed since this is not required anymore

**Pull request closed without merging**
